### ISSUE TITLE
Error: pipeline is not supported in this browser

### ISSUE THREAD

**Issue by Mihai-github** [livekit/track-processors-js#10]
Hey,

I've encountered an issue trying on `Firefox` and `Safari` to use this library. It seems like the support for those 2 browsers is not present yet. I am asking because `Chrome` and `Opera` works just fine.

Below is the error I am getting on Safari and also Firefox:
<img width="1044" alt="image" src="https://github.com/livekit/track-processors-js/assets/56633911/3a59d724-a93a-4f17-a8f2-ffda130abe53">

**Comment by lukasIO** [comment]
yeah, that's a limitation. safari an firefox don't support the necessary APIs as of now

**Comment by lukasIO** [comment]
FWIW, the processors expose an `isSupported` method that you can use. That should be more accurate than a simple browser check as it checks for the presence of the necessary APIs directly
