### ISSUE TITLE
Wrong url path for vison_wasm_internal

### ISSUE THREAD

**Issue by huynguyen-ff** [livekit/track-processors-js#17]
Hi, I have followed the example but unfortunately it doesn't work because the wrong in url fetch. Can anyone help me to fix this? Thanks a lot. Below are my code and the wrong url fetching.
<img width="449" alt="image" src="https://github.com/livekit/track-processors-js/assets/134359725/cbea16e0-63d6-4d03-a016-462369a8aabf">
<img width="752" alt="image" src="https://github.com/livekit/track-processors-js/assets/134359725/a9c656db-b6d4-4093-9d09-d5113899ba20">

**Comment by lukasIO** [comment]
hi! 

what build chain (including versions) are you using? Specifically webpack/nextjs/react version would be interesting to know.

**Comment by huynguyen-ff** [comment]
Hi, here are our dependencies:
```
{
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build-staging": "VITE_APP_ENV=staging vite build",
    "preview": "vite preview",
    "lint": "eslint src",
    "prepare": "husky install"
  },
  "dependencies": {
    "@heroicons/react": "^2.0.18",
    "@hookform/resolvers": "^3.1.0",
    "@livekit/components-react": "^1.1.8",
    "@livekit/components-styles": "^1.0.6",
    "@livekit/track-processors": "^0.2.7",
    "@mediapipe/tasks-vision": "^0.10.6",
    "axios": "^1.3.5",
    "classnames": "^2.3.2",
    "date-fns": "^2.30.0",
    "livekit-client": "^1.13.3",
    "lodash": "^4.17.21",
    "prettier": "^2.8.7",
    "react": "^18.2.0",
    "react-audio-player": "^0.17.0",
    "react-chat-elements": "^12.0.10",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.43.9",
    "react-router-dom": "^6.10.0",
    "react-select": "^5.7.3",
    "react-toastify": "^9.1.2",
    "react-use-websocket": "^4.3.1",
    "zod": "^3.21.4",
    "zustand": "^4.3.7"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.195",
    "@types/node": "^18.15.11",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react": "^3.1.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.38.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^8.0.0",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.1",
    "typescript": "^4.9.3",
    "vite": "^4.2.0",
    "vite-plugin-eslint": "^1.8.1"
  }
}

```

**Comment by huynguyen-ff** [comment]
Here is our tsconfig.json:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "src"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Comment by huynguyen-ff** [comment]
So I guess the answer is ESNext, correct me if I do not understand you correctly 😄.

**Comment by lukasIO** [comment]
hm, no `ESNext` should be fine. Does this only happen when using `vite dev` ?
Might be connected to that. You can try
1. vite preview and see if that changes things
2. vite build and serve it with a  http server

but it might also be that vite is trying to do some optimisations/misinterprets the URL.

**Comment by huynguyen-ff** [comment]
Hi, thanks for your support. I have tried both of your above approach and still meet the same error, although I have user `serve` package and host at port 3000. Below is my network log for that.
<img width="530" alt="image" src="https://github.com/livekit/track-processors-js/assets/134359725/4ab4d25b-1e06-493a-a61d-94e51f5966ca">

**Comment by jonkad** [comment]
Hi @lukasIO 

I've got the same issue with vue3. It seams to be an issue with @mediapipe/tasks-vision. 
Here is an simple example to demonstrate the JsLoader issue: [vue3-livekit-tasks-vision example](https://github.com/jonkad/vue3-livekit-tasks-vision)
