### ISSUE TITLE
Virtual and blur background are not shown in the Egress

### ISSUE THREAD

**Issue by absyah** [livekit/track-processors-js#19]
Thank you for this good work. I finally made this works with the video conference to have virtual background.

But are there any approaches to make this works with Egress too? I tried to broadcast it via RTMP but the virtual background is not shown on the viewer.

Thanks!

**Comment by lukasIO** [comment]
what egress mode are you trying this with? 
It should definitely also work for egress, as the blurring happens client side and the video gets sent to the LiveKit server already blurred .

**Comment by absyah** [comment]
@lukasIO I'm closing this, as you said that it should be definitely work for egress. I've implemented it and it works. Thank you!
