### ISSUE TITLE
Missing dependencies after install

### ISSUE THREAD

**Issue by CSantosM** [livekit/track-processors-js#24]
After install the library into an angular project, multiple errors appear in building time. 

Installing the `mediapipe` dependencies manually, the problem is fixed. 

This is why the track-processor library doesn’t install de necessary dependencies in its installation because they are not included as peer dependencies. Reference #23 

Dependencies version: 
"livekit-client": "1.12.3",
"typescript": "5.0.4"

**Comment by lukasIO** [comment]
> because they are not included as peer dependencies

I don't think this is true. Do you have any docs/articles that talk about this for reference?

Please provide more information about what package manager you are using. Also install logs and a reproduction repository would be helpful.

**Comment by CSantosM** [comment]
My apologies. 
Upon a thorough review of the installation and building process, I've come to the realization that everything is functioning as intended.
