### ISSUE TITLE
Real time change

### ISSUE THREAD

**Issue by nums** [livekit/track-processors-js#25]
I don't see how we can change the background image of the BackgroundTransformer without creating a destory.
The idea would be to be able to update the background image in real time without having to reset it all.

**Comment by lukasIO** [comment]
Hi! 
That's currently not possible, but would be a nice improvement!
If that's something you would like to contribute, let me know.

**Comment by nums** [comment]
Hello,

Here: https://github.com/livekit/track-processors-js/pull/26

**Comment by lukasIO** [comment]
Thanks, how were you planning to call that update function?

**Comment by nums** [comment]
For example when you want to change the background image or to switch between blur to image background.
The update is more quick than a complete destroy and re initialization of transformer

**Comment by lukasIO** [comment]
Sorry, should have clarified what I mean:
Did you test these changes? I think the update function is currently not exposed from the `VirtualBackground` processor, which makes it impossible to use this API for users of the package.

**Comment by nums** [comment]
Sorry, I did not understand.

But yes, I made few tests and it is working great, below is an example of use. (after 5 secondes, the background switch from blur to background image)

```javascript
let localVideoTrack = new LocalVideoTrack(videoTrack);
let backgroundTransformer = new BackgroundTransformer({
    blurRadius: 50
});
let pipeline = new ProcessorPipeline([backgroundTransformer], 'virtualbackground');        
await localVideoTrack.setProcessor(pipeline);         

setTimeout(() => {
  backgroundTransformer.update({
    imagePath: './samantha-gades-BlIhVfXbi9s-unsplash.jpg'
  });
}, 5000);
```

**Comment by lukasIO** [comment]
Got it, but the `pipeline` in your example is what's currently exposed to users, which does not expose this update method. Ideally we'd want to have a way for users to call that function directly in there, or, alternatively return the `updateBackground` method somehow additionally on the VirtualBackground processor pipeline

**Comment by dnetteln** [comment]
I would also be interested in any progress on this. Changing the background images without tearing down the whole transformer would be great!

**Comment by brokeboiflex** [comment]
> [#32](https://github.com/livekit/track-processors-js/pull/32) implements this by allowing you to do
> 
> const virtualB = VirtualBackground(imagePath);
> 
> virtualB.updateTransformerOptions({ imagePath: newImagePath });

I believe that `updateTransformerOptions` function is broken - it switches from image to blur with no problem, but its impossible to use it to switch from blur to image

**Comment by 1egoman** [comment]
@brokeboiflex As a FYI - something fairly similar to your adjustment was merged recently as part of another change! https://github.com/livekit/track-processors-js/pull/94/files#diff-131fba9244ff263a7718a11c353f091482ce65d24ae462309e6dd1d528645148R162-R171
