### ISSUE TITLE
[Feature request] Configurable model sources

### ISSUE THREAD

**Issue by ume-graham** [livekit/track-processors-js#34]
Hey, thanks for your work on this plugin!

I'm having some trouble with the hardcoded fetches out to https://cdn.jsdelivr.net ([1](https://github.com/livekit/track-processors-js/blob/4c92414b0fab07ae7eb9e0e9adac1c0b4ef644fc/src/transformers/BackgroundTransformer.ts#L39), [2](https://github.com/livekit/track-processors-js/blob/4c92414b0fab07ae7eb9e0e9adac1c0b4ef644fc/src/transformers/MediaPipeHolisticTrackerTransformer.ts#L32)). Although this is nice for folks who are just trying to get things up and running quickly, it's a little uncomfortable for those of us who have to enforce strict content security policies. There's a lot of code on jsdelivr, and I'd prefer to not have to mark it all as trusted! On its own, it's not _awful_, since it only needs `connect-src` permission, but when you combine it with the `script-src blob:` that seems to be required by `@livekit/krisp-noise-filter`, it starts to become worrying. You guys seem pretty trustworthy, but this is JS - we can't always trust the dependencies of our dependencies of our dependencies not to fetch some code from jsdelivr, stuff it into a blob, and execute it.

It would be ideal if there were a way to pass in some configuration to the plugin designating alternate source(s) for `@mediapipe/tasks-vision` and `@mediapipe/holistic`. That way, we could mirror the dependencies ourselves and not have to allow connections to jsdelivr.

**Comment by lukasIO** [comment]
@ume-graham that makes sense, can you check #34 to see if that would fit your needs?

**Comment by ume-graham** [comment]
Yup, that should work! Thanks @lukasIO!

**Comment by conroywhitney** [comment]
@lukasIO -- would you consider hosting the WASM on one of your CDNs so y'all can lock-step it with this npm package but we can still avoid using jsdelivr? or is there another alternative to a CDN altogether?
