### ISSUE TITLE
GPU error on older devices

### ISSUE THREAD

**Issue by AurimasG12** [livekit/track-processors-js#39]
As a developer I want to identify, which devices can use BackgroundBlur or VirtualBackground, but at this moment, as a user, I can use blur, but it fails.

Device: Samsung Galaxy S8 Android - 7. I'm using this device via BrowserStack, but also we have had reports with other Android devices.

Logs:
[blurLogs.log](https://github.com/livekit/track-processors-js/files/15402526/blurLogs.log)

**Comment by lukasIO** [comment]
Yeah, this would be great! 
Currently we only try to detect support by checking for the presence of `OffscreenCanvas` in the browser, which is not ideal. 
It would be best if Google Mediapipe would expose an `isSupported()` method that checks for browser support. As far as I know this currently doesn't exist for mediapipe. 
You can override the GPU use by setting `segmenterOptions.delegate = 'CPU'` on the processor options. But this doesn't really help out of the box to figure out which delegate is supported for which device.
