### ISSUE TITLE
setProcessor not working

### ISSUE THREAD

**Issue by Mihai-github** [livekit/track-processors-js#4]
Hey, I am trying to implement this library into our project but I'm having some issues with an error appearing while trying to use the examples provided, the error is attached to this ticket.
Is something that I did not do or there's something different happening in there

![image](https://github.com/livekit/track-processors-js/assets/56633911/a6639fb2-cd3b-4b0c-a278-39a7a0da0216)

Thanks!

**Comment by lukasIO** [comment]
there was a problem with the version being hardcoded as a string. does the error still happen to you on `v0.1.2` ?

**Comment by lukasIO** [comment]
the logs you posted are from v0.1.1,  maybe you need to clear your node_modules?

**Comment by lukasIO** [comment]
hmm. something was weird with the dist folder, I re-released, can you try again with 0.1.3?

**Comment by Mihai-github** [comment]
Yes, but I don't know why but I keep getting now when importing the module

`Cannot find module '@livekit/track-processors' or its corresponding type declarations.`

for `import {BackgroundBlur, VirtualBackground} from '@livekit/track-processors';`

**Comment by Mihai-github** [comment]
@lukasIO So there's a issue with the latest release, check please the below screen shoots added:

v0.1.2
![image](https://github.com/livekit/track-processors-js/assets/56633911/084ec98f-2a92-4f71-881e-1f9e203dcdc7)

and v0.1.3
![image](https://github.com/livekit/track-processors-js/assets/56633911/231eeaad-265d-4b28-ae0b-9b043527fc81)

**Comment by lukasIO** [comment]
thanks! just realised it, fixed in the latest version. sorry again!

**Comment by Mihai-github** [comment]
Thanks, @lukasIO, works now with the v0.1.4.
