### ISSUE TITLE
Error logged when stopping the Blur Effect

### ISSUE THREAD

**Issue by lebaudantoine** [livekit/track-processors-js#47]
First, thank you for your incredible work!

I encountered an error while running the sample app. It was logged to my console right after I stopped the Blur effect. I'm using macOS Apple M2 Pro Ventura 13.0 with Chrome version 128.0.6613.138 (official build) (arm64).

The error originates from this line in the code: [ProcessorWrapper.ts#L88](https://github.com/livekit/track-processors-js/blob/365606b629b177d9bb3440876151b436d32ecad9/src/ProcessorWrapper.ts#L88). I haven't had a chance to investigate further, but here's the error message:

```
ProcessorWrapper.ts:88 error when trying to pipe TypeError: Failed to execute 'write' on 'UnderlyingSinkBase': Empty video frame.
```
![Capture d’écran 2024-09-20 à 14 25 46](https://github.com/user-attachments/assets/e552fa68-33f8-48aa-85de-31928ba79fae)

**Comment by antonzaharia** [comment]
Any updates on this? 🙏

**Comment by lukasIO** [comment]
This error is safe to ignore

**Comment by brokeboiflex** [comment]
> This error is safe to ignore

I'm not an expert but this error is probably easy to fix too
