### ISSUE TITLE
delegate to GPU not working?

### ISSUE THREAD

**Issue by sgrund14** [livekit/track-processors-js#49]
Hello

Wondering, should the `{ delegate: 'GPU' }`  option be working for `BlurBackground` and `VirtualBackground`?

I am using it, but the backgrounds are still vastly increasing my CPU usage

Thanks!

**Comment by lukasIO** [comment]
the option shifts some workload to the GPU (namely internal mediapipe workload), but due to the fact that not all computation is done on the GPU (#44 ) it still uses quite a bit of CPU. Will close this issue as the underlying issue is the same as #44

**Comment by sgrund14** [comment]
@lukasIO got it, thanks

Out of curiosity, have you attempted to incorporate a WebGL pipeline like in https://github.com/livekit/track-processors-js/issues/44?

I'm thinking about forking and incorporating myself because my use case is already pretty CPU intensive, so it'd be good to be able to offload as much as we can. Have you tried before / run into any roadblocks?

**Comment by lukasIO** [comment]
No, I haven't attempted it yet. 
If you succeed we would of course welcome a PR and incorporate the webGL mode into the official one
